# Generated by Django 5.2.12 on 2026-03-06 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('head_yaw', models.FloatField(blank=True, null=True)),
                ('head_pitch', models.FloatField(blank=True, null=True)),
                ('head_roll', models.FloatField(blank=True, null=True)),
                ('gaze_direction', models.CharField(blank=True, max_length=30)),
                ('attention_zone', models.CharField(default='green', max_length=10)),
                ('blink_rate', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.FloatField(default=0)),
                ('sad', models.FloatField(default=0)),
                ('angry', models.FloatField(default=0)),
                ('surprise', models.FloatField(default=0)),
                ('disgust', models.FloatField(default=0)),
                ('neutral', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiologicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(null=True)),
                ('stress_level', models.FloatField(null=True)),
                ('respiration', models.FloatField(null=True)),
                ('blood_oxygen', models.FloatField(null=True)),
                ('hrv', models.FloatField(null=True)),
            ],
        ),
    ]
