# Generated by Django 5.2.12 on 2026-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_language',
            field=models.CharField(blank=True, default='python', help_text='Default language for coding questions (python, javascript, java, cpp)', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.IntegerField(blank=True, help_text='Per-question time limit in seconds (optional; overrides exam timer)', null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='points_awarded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Text Answer'), ('essay', 'Essay'), ('code', 'Code Answer')], default='mcq', max_length=10),
        ),
    ]
