# Generated by Django 5.2.12 on 2026-03-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_code_language_question_time_limit_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit_seconds',
            field=models.IntegerField(blank=True, help_text='Per-question time limit in seconds (optional)', null=True),
        ),
    ]
