# Generated by Django 5.2.12 on 2026-03-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_question_time_limit_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code_language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_limit_seconds',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='points_awarded',
        ),
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='questions/attachments/'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='media_upload',
            field=models.FileField(blank=True, null=True, upload_to='answers/media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Descriptive / Short Answer'), ('code', 'Coding Challenge'), ('media', 'Media Upload required')], default='mcq', max_length=10),
        ),
    ]
