# Generated by Django 5.2.12 on 2026-03-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_question_code_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='examsession',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='examsession',
            name='university_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
