# Generated by Django 5.0.2 on 2026-03-09 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParrokitAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(choices=[('face_detection', 'Face Detection'), ('mobile_detection', 'Mobile Device Detection'), ('distraction_detection', 'Distraction Detection'), ('emotion_analysis', 'Emotion Analysis'), ('voice_analysis', 'Voice Analysis'), ('multi_agent', 'Multi-Agent Orchestrator')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_sessions', models.IntegerField(default=10)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringSessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('mobile_detection_count', models.IntegerField(default=0)),
                ('distraction_event_count', models.IntegerField(default=0)),
                ('face_detection_failures', models.IntegerField(default=0)),
                ('multiple_face_detections', models.IntegerField(default=0)),
                ('looking_away_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('final_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('meet_link', models.URLField(blank=True)),
                ('meet_started_at', models.DateTimeField(blank=True, null=True)),
                ('agents', models.ManyToManyField(blank=True, to='monitoring.parrokitagent')),
                ('proctors', models.ManyToManyField(blank=True, to='monitoring.proctor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('device_type_estimate', models.CharField(blank=True, max_length=50)),
                ('duration_seconds', models.FloatField(default=0)),
                ('frame_snapshot', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_detections', to='monitoring.proctoringsessionlog')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadPoseMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.FloatField(default=0.0)),
                ('yaw', models.FloatField(default=0.0)),
                ('roll', models.FloatField(default=0.0)),
                ('zone', models.CharField(choices=[('green', 'Green - Focused'), ('yellow', 'Yellow - Warning'), ('red', 'Red - Looking Away')], default='green', max_length=20)),
                ('direction', models.CharField(blank=True, max_length=50)),
                ('looking_away', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_pose_metrics', to='monitoring.proctoringsessionlog')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('happy', models.FloatField(default=0.0)),
                ('sad', models.FloatField(default=0.0)),
                ('angry', models.FloatField(default=0.0)),
                ('surprise', models.FloatField(default=0.0)),
                ('disgust', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(default='Neutral', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_profiles', to='monitoring.proctoringsessionlog')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DistractionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distraction_type', models.CharField(choices=[('HEAD_MOVEMENT', 'Excessive Head Movement'), ('EYE_GAZE', 'Eye Gaze Away'), ('POSTURE_CHANGE', 'Posture Change'), ('OBJECT_INTERACTION', 'Object Interaction'), ('ENVIRONMENT_NOISE', 'Environment Noise')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distractions', to='monitoring.proctoringsessionlog')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('MOBILE_DETECTED', 'Mobile Phone Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('NO_FACE', 'No Face Detected'), ('SUSTAINED_LOOKING_AWAY', 'Looking Away'), ('ATTENTION_WARNING', 'Attention Warning'), ('DISTRACTION_DETECTED', 'Distraction Detected'), ('VOICE_DETECTED', 'Voice/Unusual Sound'), ('SUSPICIOUS_OBJECT', 'Suspicious Object')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elapsed_time_seconds', models.FloatField(default=0)),
                ('frame_data', models.TextField(blank=True, help_text='Base64 encoded frame snapshot')),
                ('head_pose_data', models.JSONField(blank=True, default=dict)),
                ('zone_at_violation', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='monitoring.proctoringsessionlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='monitoring.proctor')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('proctor', 'session_id')},
            },
        ),
    ]
